/* Auto-generated by gen-attrs-types. DO NOT EDIT. */
/* Run: bun run gen:types */

import type { appPlugin } from './examples/app-plugin';
import type { nestedPlugin } from './examples/pages/nested-demo-plugin';
import type { Attrs as route_profile } from './examples/pages/ProfilePage.vue';
import type { Attrs as dialog_confirm } from './examples/dialogs/ConfirmDialog.vue';

declare module './libs/index' {
  interface Register {
    plugin: typeof appPlugin | typeof nestedPlugin;
  }
  interface RouteAttrsMap {
    profile: route_profile;
  }
  interface DialogAttrsMap {
    confirm: dialog_confirm;
  }
}
